SukkuShop/Areas/Admin/Controllers/ZamowieniaController.cs
#region

using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using SukkuShop.Areas.Admin.Models;
using SukkuShop.Infrastructure.Generic;
using SukkuShop.Models;

#endregion

namespace SukkuShop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public partial class ZamowieniaController : Controller
    {
        private readonly IAppRepository _appRepository;
        private readonly ApplicationDbContext _dbContext;

        public ZamowieniaController(ApplicationDbContext dbContext, IAppRepository appRepository)
        {
            _dbContext = dbContext;
            _appRepository = appRepository;
        }

        // GET: Admin/Zamowienia
        public virtual ActionResult Index()
        {
            ViewBag.SelectedOpt = 2;
            return View();
        }

        public virtual JsonResult GetOrdersList()
        {
            var orders = _appRepository.GetAll<Orders>().Select(x => new
            {
                x.Email,
                x.OrderId,
                x.OrderDate,
                x.OrderInfo,
                x.TotalPrice,
                x.UserId
            }).ToList();

            var ordersObj = orders.Select(x => new
            {
                email = x.Email,
                id = x.OrderId,
                data = x.OrderDate.ToShortDateString(),
                stan = x.OrderInfo,
                total = x.TotalPrice,
                userId = x.UserId,
                orderOpts = GetOrderChangeOptions(x.OrderInfo),
                selectedOpt = x.OrderInfo
            }).ToList();

            return Json(ordersObj, JsonRequestBehavior.AllowGet);
        }

        //[HttpPost]
        //public virtual JsonResult ChangeOrderState(int id, string value, string packageNumber)
        //{
        //    var order = _dbContext.Orders.FirstOrDefault(x => x.OrderId == id);
        //    if (order != null && order.OrderInfo != value)
        //    {
        //        order.OrderInfo = value;
        //        _dbContext.Orders.AddOrUpdate(order);
        //        _dbContext.SaveChanges();

        //        var discounvalue = ((order.OrderDetails.Sum(orderdetail => orderdetail.SubTotalPrice)*order.Discount)*
        //                            100)/100;
        //        var email = new ChangeOrderStateEmail
        //        {
        //            To = order.Email,
        //            Id = order.OrderId,
        //            State = value,
        //            StateDescription = SetStateDescription(value),
        //            PackageName = value=="Wysłane"?packageNumber:null,
        //            OrderViewModelsSummary = new OrderViewModelsSummary
        //            {
        //                Firma = order.NazwaFirmy != null,
        //                TotalTotalValue = order.TotalPrice,
        //                Discount = order.Discount,
        //                DiscountValue = discounvalue.ToString("c"),
        //                OrderPayment = new SharedShippingOrderSummaryModels
        //                {
        //                    Description = order.Payment.PaymentDescription,
        //                    Name = order.Payment.PaymentName,
        //                    Price = order.Payment.PaymentPrice
        //                },
        //                OrderShipping = new SharedShippingOrderSummaryModels
        //                {
        //                    Description = order.Shipping.ShippingDescription,
        //                    Name = order.Shipping.ShippingName,
        //                    Price = order.Shipping.ShippingPrice
        //                },
        //                UserAddressModel = new CartAddressModel
        //                {
        //                    Email = order.Email,
        //                    Imie = order.Name,
        //                    KodPocztowy = order.PostalCode,
        //                    Miasto = order.City,
        //                    NazwaFirmy = order.NazwaFirmy,
        //                    Nazwisko = order.Surname,
        //                    Nip = order.OrderNip,
        //                    Numer = order.Number,
        //                    Telefon = order.Phone,
        //                    Ulica = order.Street
        //                },
        //                OrderViewItemsTotal = new OrderViewItemsTotal
        //                {
        //                    TotalValue = order.OrderDetails.Sum(x => x.SubTotalPrice),
        //                    OrderProductList = order.OrderDetails.Select(m => new OrderItemSummary
        //                    {
        //                        Image = m.Products.IconName ?? "NoPhoto_small",
        //                        Name = m.Products.Name,
        //                        Price = m.Products.Price ?? 0,
        //                        Quantity = m.Quantity,
        //                        TotalValue = m.SubTotalPrice,
        //                        Packing = m.Products.Packing
        //                    }).ToList()
        //                }
        //            }
        //        };
        //        email.Send();
        //    }
        //    return Json(GetOrderChangeOptions(value), JsonRequestBehavior.AllowGet);
        //}

        public virtual PartialViewResult ChangeOrderStateFromDetails(int id, string value, string packageNumber)
        {
            var order = _appRepository.GetSingle<Orders>(x => x.OrderId == id);

            if (order != null && order.OrderInfo != value)
            {
                var orderDetails = _appRepository.GetAll<OrderDetails>(x => x.OrderId == order.OrderId).ToList();
                if (value == "Wysłane")
                {
                    foreach (var item in orderDetails)
                    {
                        var product = _appRepository.GetSingle<Products>(j => j.ProductId == item.ProductId);
                        product.ReservedQuantity -= item.Quantity;
                        product.Quantity -= item.Quantity;
                        _dbContext.Products.AddOrUpdate(product);
                    }
                }
                order.OrderInfo = value;
                _dbContext.Orders.AddOrUpdate(order);
                _dbContext.SaveChanges();
                ViewBag.AjaxOrderState = order.OrderInfo;
                ViewBag.OrderId = id;
                var discounvalue = ((order.OrderDetails.Sum(orderdetail => orderdetail.SubTotalPrice)*order.Discount)*
                                    100)/100;

                var payment = _appRepository.GetSingle<PaymentType>(x => x.PaymentId == order.PaymentId);
                var shipping = _appRepository.GetSingle<ShippingType>(x => x.ShippingId == order.ShippingId);

                var email = new ChangeOrderStateEmail
                {
                    To = order.Email,
                    Id = order.OrderId,
                    State = value,
                    StateDescription = SetStateDescription(value),
                    PackageName = value == "Wysłane" ? packageNumber : null,
                    OrderViewModelsSummary = new OrderViewModelsSummary
                    {
                        Firma = order.NazwaFirmy != null,
                        TotalTotalValue = order.TotalPrice,
                        Discount = order.Discount,
                        DiscountValue = discounvalue.ToString("c"),
                        OrderPayment = new SharedShippingOrderSummaryModels
                        {
                            Description = payment.PaymentDescription,
                            Name = payment.PaymentName,
                            Price = order.FreeShippingPayment ? 0 : payment.PaymentPrice
                        },
                        OrderShipping = new SharedShippingOrderSummaryModels
                        {
                            Description = shipping.ShippingDescription,
                            Name = shipping.ShippingName,
                            Price = order.FreeShippingPayment ? 0 : shipping.ShippingPrice
                        },
                        UserAddressModel = new CartAddressModel
                        {
                            Email = order.Email,
                            Imie = order.Name,
                            KodPocztowy = order.PostalCode,
                            Miasto = order.City,
                            NazwaFirmy = order.NazwaFirmy,
                            Nazwisko = order.Surname,
                            Nip = order.OrderNip,
                            Numer = order.Number,
                            Telefon = order.Phone,
                            Ulica = order.Street
                        },
                        OrderViewItemsTotal = new OrderViewItemsTotal
                        {
                            TotalValue = orderDetails.Sum(x => x.SubTotalPrice),
                            OrderProductList = orderDetails.Select(m =>
                            {
                                var product = _appRepository.GetSingle<Products>(k => k.ProductId == m.ProductId);
                                return new OrderItemSummary
                                {
                                    Image = product.IconName ?? "NoPhoto_small",
                                    Name = product.Name,
                                    Price = product.Price ?? 0,
                                    Quantity = m.Quantity,
                                    TotalValue = m.SubTotalPrice,
                                    Packing = product.Packing
                                };
                            }).ToList()
                        }
                    }
                };
                email.Send();
            }
            var list = GetOrderDetailsStateList(value);

SukkuShop/Areas/Admin/Views/Zamowienia/Index.cshtml
@{
    ViewBag.Title = "Lista zamówień";
}
@Styles.Render("~/Areas/Admin/Content/css/AdminOrdersList.min.css")
@Scripts.Render("~/Scripts/angular.min.js")
@Scripts.Render("~/Areas/Admin/Scripts/ordersListAngular.min.js")

<div ng-app="adminApp">
    <div ng-controller="AdminOrderCtrl" ng-init="init()">
        <div class="main-cont">
            <div style="margin-bottom: 20px">
                <input type="checkbox" class="css-checkbox" ng-model="przyjete" id="przyjete" ng-change="filterByCheckboxes()" />
                <label for="przyjete" class="css-label" style="margin-left:0">TYLKO PRZYJĘTE</label>
                <input type="checkbox" class="css-checkbox" ng-model="zakonczone" id="zakonczone" ng-change="filterByCheckboxes()" />
                <label for="zakonczone" class="css-label">TYLKO ZAKOŃCZONE</label>
                <input type="checkbox" class="css-checkbox" ng-model="oczekujace" id="oczekujace" ng-change="filterByCheckboxes()" />
                <label for="oczekujace" class="css-label">TYLKO OCZEKUJĄCE NA WPŁATĘ</label>
                <input type="checkbox" class="css-checkbox" ng-model="realizowane" id="uregulowane" ng-change="filterByCheckboxes()" />
                <label for="uregulowane" class="css-label">TYLKO REALIZOWANE</label>
                <div style="clear:both"></div>
            </div>
            <div class="search-box">
                <input type="text" ng-model="textFilter" ng-change="filterByName()" placeholder="WYSZUKAJ" />
            </div>
            <table class="main-table">
                <thead id="plz">
                    <th>ID Zamówienia <a href="" ng-class="{'selected': selectedIndex==1}" ng-click="orderByMhm('id',false,1)"><div class="icon-arrow-up up"></div></a><a href="" ng-class="{'selected': selectedIndex==2}" ng-click="orderByMhm('id',true,2)"><div class="icon-arrow-down down"></div></a></th>
                    <th>Email klienta <a href="" ng-class="{'selected': selectedIndex==3}" ng-click="orderByMhm('email',false,3)"><div class="icon-arrow-up up"></div></a><a href="" ng-class="{'selected': selectedIndex==4}" ng-click="orderByMhm('email',true,4)"><div class="icon-arrow-down down"></div></a></th>
                    <th>Data złożenia<a href="" ng-class="{'selected': selectedIndex==5}" ng-click="orderByMhm('data',false,5)"><div class="icon-arrow-up up"></div></a><a href="" ng-class="{'selected': selectedIndex==6}" ng-click="orderByMhm('data',true,6)"><div class="icon-arrow-down down"></div></a></th>
                    <th>Stan zamówienia</th>
                    <th>Wartość</th>
                    <th class="blank"></th>
                </thead>
                <tbody>
                    <tr ng-repeat="item in ordersList">
                        <td>{{item.id}}<a ng-href="@Url.Action("SzczegolyZamowienia","Zamowienia")/{{item.id}}"><div class="icon-eye-open icon"></div></a></td>
                        <td>{{item.email}}<a ng-if="item.userId!=null" ng-href="@Url.Action("Szczegóły", "Klienci")/{{item.userId}}"><div class="icon-eye-open icon"></div></a></td>
                        <td>{{item.data}}</td>
                        <td>
                            <div ng-if="item.stan!='Anulowane' && item.stan!='Wysłane'">
                                {{item.stan}}
                            </div>

                            <div ng-if="item.stan=='Anulowane'" style="color:red">Anulowane</div>
                            <div ng-if="item.stan=='Wysłane'" style="color:green">Wysłane</div>
                        </td>
                        <td>{{item.total}} PLN</td>
                        <td><div class="save-text"><a target="_blank" href="@Url.Action(MVC.Admin.Zamowienia.DownloadInvoice())">POBIERZ FAKTURĘ</a></div></td>
                    </tr>
                </tbody>
            </table>
            <div id="paginator" ng-if="pages>1">
                <ul class="shop-paginator">
                    <li>
                        <div class="paging-arrow-left" ng-click="setPage(currentPage-1)"></div>
                    </li>
                    <li class="inner-paginator" ng-repeat="page in tableOfPages" style="display: inline-block">
                        <div ng-if="page==currentPage">
                            <div class="paginator-box" style="font-weight: bold" ng-click="setPage($index+1)">{{page}}</div>
                        </div>
                        <div ng-if="page!=currentPage">
                            <div class="paginator-box" ng-click="setPage($index+1)">{{page}}</div>
                        </div>
                    </li>
                    <li>
                        <div class="paging-arrow-right" ng-click="setPage(currentPage+1)"></div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

SukkuShop/Areas/Admin/Views/Zamowienia/SzczegolyZamowienia.cshtml
@model SukkuShop.Areas.Admin.Models.AdminOrderViewModelsSummary

@{
    ViewBag.Title = "SzczegółyZamówienia";
}

<div class="order-container">
    <div class="title">Podgląd zamówienia</div>
    <div class="options-container">
        <div class="left-box">
            Data zamówienia: <p>@Model.OrderDat</p>
        </div>
        <div class="right-box" id="id-box">
            Numer zamówienia: <p>@Model.Id</p>
        </div>
        <div class="left-box" id="replace">

            @if (Model.OrderInfo == "Anulowane")
            {@:Stan zamówienia:
                <p style="color: red">@Model.OrderInfo</p>
            }
            else if (Model.OrderInfo == "Wysłane")
            {@:Stan zamówienia:
                <p id="order-info" style="color: green">@Model.OrderInfo</p>
            }
            else
            {
                using (Ajax.BeginForm(MVC.Admin.Zamowienia.ChangeOrderStateFromDetails(), new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "replace", HttpMethod = "POST", OnSuccess = "endAjaxLoader()" }, new { id = "changeStateForm" }))
                {
                    <span style="float:left;margin:0 10px 0 80px">Stan zamówienia:</span>
                    <div class="styled-select">
                        @Html.DropDownList("value", (List<SelectListItem>)ViewBag.OrderStateList, new{id="stateDropdown"})
                    </div>
                    @Html.HiddenFor(x=>x.Id)
                    
                    <a href="" id="submitOrderState" style="float:left;margin-left: 10px">ZAPISZ</a>
    <div id="number-box" style="visibility: hidden;clear:both;padding-top:10px;">
        <span style="float:left;margin:0 10px 0 80px">Numer listu:</span>
        @Html.TextBox("packageNumber", null, new { style = "float: left;height: 20px;font-family: Segoe UI;font-size: 14px;line-height: 20px;width: 200px;border: 1px solid #f89b1d;" })
    </div>

                }

            }
        </div>
        <div class="right-box" id="anuluj-box">
            <a href="@Url.Action(MVC.Admin.Zamowienia.DownloadInvoice())">Pobierz fakturę</a>
            <div style="clear:both;color:red;visibility: hidden;padding-top:10px" id="numberAlert">Podaj numer listu przewozowego!</div>
        </div>
        <div class="clear" style="clear:both">&nbsp; </div>
    </div>
    <div class="order-title">Waga zamówienia: @Model.OrderWeight kg</div>
    <table class="order-table" cellspacing="0">
        <thead>
            <tr>
                <th>Zamówione produkty</th>
                <th>Cena</th>
                <th>Ilość</th>
                <th>Suma</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.OrderViewItemsTotal.OrderProductList)
            {
                <tr>
                    <td>
                        <img img src="@Url.Content("~/Content/Images/Shop/"+item.Image+".jpg")" alt="produkt" />
                        <div class="custom-product-text-container">
                            <p>
                                <span style="font-size: 18px; line-height: 25px;">@item.Name</span>
                            </p>
                        </div>
                    </td>
                    <td>@item.Price zł</td>
                    <td>@item.Quantity szt. x @item.Packing</td>
                    <td>@item.TotalValue zł</td>
                </tr>
            }
        </tbody>
    </table>
    <div class="products-price-summary"><span style="margin-right: 15px">Razem</span> @Model.OrderViewItemsTotal.TotalValue zł</div>
    <div class="order-title">Dostawa</div>
    <div class="order-summary-header-text">@Model.OrderShipping.Name</div>
    <div class="shipping-price">@Model.OrderShipping.Price zł</div>
    <div class="clear">&nbsp;</div>
    <div class="order-title">Adres dostawy</div>
    @if (Model.Firma)
    {
        <div class="order-summary-header-text">@Model.UserAddressModel.NazwaFirmy <br />NIP @Model.UserAddressModel.Nip</div>
    }
    else
    {
        <div class="order-summary-header-text">@Model.UserAddressModel.Imie @Model.UserAddressModel.Nazwisko</div>
    }

    <div class="order-summary-description-text">
        ul. @Model.UserAddressModel.Ulica @Model.UserAddressModel.Numer<br />
        @Model.UserAddressModel.KodPocztowy @Model.UserAddressModel.Miasto<br />
        Tel.: @Model.UserAddressModel.Telefon<br />
    </div>

    <div class="order-title" style="clear: both">Płatność</div>
    <div class="order-summary-header-text">@Model.OrderPayment.Name</div>
    <div class="shipping-price">@Model.OrderPayment.Price zł</div>
    <div class="order-title" style="clear: both">Uwagi Klienta</div>
    <div class="order-summary-header-text" style="width:100%">@Model.UserOrderInfo</div>
    @if (Model.UserId != null)
    {
        <div class="order-title">Konto klienta</div>
        <div class="order-summary-header-text" style="width:Auto;margin-right: 10px"><strong>Email:</strong> @Model.UserAddressModel.Email</div>
        <a href="@Url.Action(MVC.Admin.Klienci.Szczegóły((int) Model.UserId))"><div class="icon-eye-open" style="font-size:25px;color:grey"></div></a>
    }
    <div class="order-title" style="border-top: #f89b1d 1px solid">Podsumowanie</div>
    <ul id="products-summary" style="padding-bottom: 20px;">
        <li>
            <div id="price-box">Produkty: @Model.OrderViewItemsTotal.TotalValue ZŁ</div>
        </li>
        <li>
            <div id="price-box">Wysyłka: @Model.OrderShipping.Price ZŁ</div>
        </li>
        <li>
            <div id="price-box">Płatność: @Model.OrderPayment.Price ZŁ</div>
        </li>
        <li>
            <div id="price-box">Rabat: @Model.DiscountValue (@Model.Discount%)</div>
        </li>
        <li class="summary-text-bold">
            <div id="price-box">Razem: <span style="color: #f89b1d">@Model.TotalTotalValue</span></div>
        </li>
    </ul>
    <a href="@Url.Action(MVC.Admin.Zamowienia.Index())">
        <div id="triangle-left-big" style="margin-top: 0"></div><div class="order-title-ending" style="float: left;">POWRÓT</div>
    </a>

</div>


@Styles.Render("~/Areas/Admin/Content/css/AdminOrderDetails.min.css")
@Scripts.Render("~/Areas/Admin/Scripts/AdminOrderDetails.js")

SukkuShop/Areas/Admin/Views/Zamowienia/_ChangeOrderStateFromDetails.cshtml
@model List<SelectListItem>
@if (ViewBag.AjaxOrderState == "Anulowane")
{@:Stan zamówienia:
    <p style="color: red">@ViewBag.AjaxOrderState</p>
}
else if (ViewBag.AjaxOrderState == "Wysłane")
{@:Stan zamówienia:
    <p id="order-info" style="color: green">@ViewBag.AjaxOrderState</p>
}
else
{
    using (Ajax.BeginForm(MVC.Admin.Zamowienia.ChangeOrderStateFromDetails(), new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "replace", HttpMethod = "POST", OnSuccess = "endAjaxLoader()" }, new { id = "changeStateForm" }))
    {
        <span style="float:left;margin:0 10px 0 80px">Stan zamówienia:</span>
        <div class="styled-select">
            @Html.DropDownList("value", Model, new { id = "stateDropdown" })
        </div>
        @Html.Hidden("Id", (int)ViewBag.OrderId)
        <a href="" id="submitOrderState" style="float:left;margin-left: 10px">ZAPISZ</a>
        <div id="number-box" style="visibility: hidden;clear:both;padding-top:10px;">
            <span style="float:left;margin:0 10px 0 80px">Numer listu:</span>
            @Html.TextBox("packageNumber", null, new { style = "float: left;height: 20px;font-family: Segoe UI;font-size: 14px;line-height: 20px;width: 200px;border: 1px solid #f89b1d;" })
        </div>
    }

}